---
title: "Sales Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE) 

library(flexdashboard)

# Core
library(tidyverse)

# Interactive Visualizations
library(plotly)

# Spatial Data
library(raster)
library(sf)
library(dplyr)
library(lubridate)
library(shinyWidgets)

```

```{r echo=FALSE}
format_to_euro <- function(x, suffix = " €") {

  scales::dollar(x,
                 suffix       = suffix,
                 prefix       = "",
                 big.mark     = ".",
                 decimal.mark = ",")
}

euro_format <- function(scale        = 1,
                        prefix       = "",
                        suffix       = " €",
                        big.mark     = ".",
                        decimal.mark = ",") {

  scales::dollar_format(suffix       = suffix,
                        prefix       = prefix,
                        big.mark     = big.mark,
                        decimal.mark = decimal.mark,
                        scale        = scale)

}
```


```{r}
# Bike data
bikes_tbl      <- readRDS("01_data/bikes_tbl.rds")
bikeshops_tbl  <- readRDS("01_data/bikeshops_tbl.rds")
orderlines_tbl <- readRDS("01_data/orderlines_tbl.rds")

bike_orderlines_tbl <- orderlines_tbl %>%
    left_join(bikes_tbl,     by = c("product_id" = "bike_id")) %>%
    left_join(bikeshops_tbl, by = c("customer_id" = "bikeshop_id")) %>%
    mutate(total_price = price_euro * quantity)


# German spatial data
# German spatial data
# germany_sp <- getData('GADM', country='DE', level=1) broken link
germany_sp <- readRDS("01_data/gadm36_DEU_1_sp.rds")
germany_sf <- st_as_sf(germany_sp) %>% 
  
                  # Add english names
                  mutate(VARNAME_1 = ifelse(is.na(VARNAME_1), NAME_1, VARNAME_1)) 
```


Column {.sidebar}
-----------------------------------------------------------------------

```{r}
DateSeq = seq(as.Date("2015-01-07"), Sys.Date(), "day")
dateRangeInput("dateRange", "Date Range", format = "yyyy-mm-dd", start=min(DateSeq), end=max(DateSeq))

```


```{r}
checkboxGroupButtons("bike_type", "Bike Type",
                           choices = c("All", "Road", "Mountain"),
                           selected = "All",
                           status = "primary")


```

```{r}
pickerInput("bike_family", "Bike Family",
            choices = c("All", unique(bike_orderlines_tbl$category_2)),
            selected = "All",
            multiple = TRUE)
```


```{r}
actionButton("apply_filters", "Apply Filters", icon = icon("filter"))

```


Column {data-width=1000}
---------------------------------------------------------------

### By State

```{r}
# Reactive expression to filter data when the Apply button is clicked
filtered_data <- eventReactive(input$apply_filters, {
  req(input$dateRange)  # Ensure dateRange input is available
  req(input$bike_type)  # Ensure bike_type input is available
  req(input$bike_family)  # Ensure bike_family input is available

  bike_orderlines_tbl %>%
  filter(order_date >= input$dateRange[1] & order_date <= input$dateRange[2]) %>%
  filter(if ("All" %in% input$bike_type || length(input$bike_type) == 0) TRUE else category_1 %in% input$bike_type) %>%
  filter(if ("All" %in% input$bike_family || length(input$bike_family) == 0) TRUE else category_2 %in% input$bike_family) %>%
  group_by(state) %>%
  summarise(total_revenue = sum(total_price)) %>%
  ungroup() %>%
  right_join(germany_sf, by = c("state" = "VARNAME_1")) %>%
  mutate(total_revenue = ifelse(is.na(total_revenue), 0, total_revenue)) %>%
  mutate(label_text = str_glue("State: {state}
                               Revenue: {format_to_euro(total_revenue)}")) %>%
  st_as_sf()
})

# Render the plot based on filtered data
output$geo_plot_tbl <- renderPlot({
  data <- filtered_data()
 plot_ly(
      data = data,
      type = 'choroplethmapbox',
      geojson = geojsonio::geojson_list(geo_plot_tbl),
      locations = ~state,
      featureidkey = "properties.VARNAME_1",
      color = ~total_revenue,
      colors = "Blues",
      hoverinfo = 'text',
      text = ~label_text,
      colorbar = list(title = "Total Revenue")
    ) %>%
      layout(
        mapbox = list(
          center = list(lon = 10, lat = 51),
          zoom = 4
        )
      )
})
```


```{r}

#geo_plot_tbl <- bike_orderlines_tbl %>% 
#                  group_by(state) %>%
#                  summarise(total_revenue = sum(total_price)) %>%
#                  ungroup() %>%
#                  right_join(germany_sf, by = c("state" = "VARNAME_1")) %>% 
#                  mutate(total_revenue = ifelse(is.na(total_revenue), 0, total_revenue)) %>% 
#                  mutate(label_text = str_glue("State: {state}
#                                         Revenue: {format_to_euro(total_revenue)}")) %>% 
#                  st_as_sf()
```


```{r}

```

```{r}
plotOutput("geo_plot_tbl")
```


Column {data-width=1000}
---------------------------------------------------------------

### Over Time
